spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/taskmaster?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8081